credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$.MxbrLpp941G5JKmtmHkve41pBUg88a0gQfK5TlwB4x.PAjUn8zOa'
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$C.4DGdeqvMIL3ZAQjCyVbu8zCtI1G1aQwFnMIXKC8kzaiXGN5kRUa'
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com